# Generated by Django 5.1.2 on 2024-10-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_passanger'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passanger',
            new_name='Passenger',
        ),
    ]
