# Generated by Django 5.1.2 on 2024-10-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_passenger_flights'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('flights', models.ManyToManyField(blank=True, related_name='food', to='apps.flight')),
            ],
        ),
    ]
